name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Récupération dynamique des dépendances
      run: npm ci

    - name: Execution du Linter
      run: .\node_modules\.bin\eslint .

    - name: Execution des tests via Jest
      run: .\node_modules\.bin\jest

    - name: Execution du script "node index.js"
      run: npm run build
